version: '3.7'

services:
    # サービス名は自由に設定
    django:
        # appディレクトリの中から`Dockerfile`を探す
        build: ./dm
        # サービス起動後に入力されるコマンドを設定
        command: python manage.py runserver 0.0.0.0:5000
        # データを永続化させる場合の設定。`host:container`でパスを記載
        volumes:
            - ./dm/:/usr/src/dm/
        # 開放するポートを指定。`host:container`でポートを記載
        ports:
            - 5000:5000
        # 環境変数を指定
        environment:
            # 1ならデバックモード
            - DEBUG=1
            # setting.pyに記載されているSECRET_KEYを記入
            - SECRET_KEY=os.environ.get('SECRET_KEY')